### ISSUE TITLE
Urgent Help Needed in iOS Production Release

### ISSUE THREAD

**Issue by akshaydesai2010** [nizwar/openvpn_flutter#103]
Hello openvpn_flutter Team,

I hope this message finds you well. I wanted to report a critical issue we are facing with the openvpn_flutter repository in our Flutter based iOS production app.

We recently encountered a rejection due to guideline 4.3, specifically related to spam issues. This rejection has halted our progress, and we are unable to move forward with our release. We are concerned about this issue and are seeking urgent assistance.

Could you please advise if anyone else has faced similar problems or if there are any known solutions or workarounds? We understand the importance of resolving this issue promptly, even if it requires paid support.

Your prompt attention and assistance in this matter would be greatly appreciated.

More details on Design Spam Issue 4.3 : https://developer.apple.com/app-store/review/guidelines/#spam

**Comment by dphans** [comment]
Usually, reject cause of "spam" are not caused by the library.
The most common issue is that your app's functionality is too simple (I think only VPN connection is selected in the list), which means that there are too many other apps that even have the same UI as yours.

How to fix:
- A special application on the AppStore that few other applications have ever exploited; add more functionality to your app "unique". (70%)
- Contact for Apple Review support for more information, point which features cause of spam. (20%)
